### ISSUE TITLE
Request body content can only be read once

### ISSUE THREAD

**Issue by jorygeerts** [wellrestedphp/wellrested#15]
I expected the following code to output the request body twice:

```
echo $request->getBody()->getContents(); // Does output the body
echo $request->getBody()->rewind();
echo $request->getBody()->getContents(); // Does nothing
```

After looking trough the source code, I found `ServerRequest::getStreamForBody()`, which uses `php://input` as data source.
Sadly, even though `stream_get_meta_data` says seeking is OK and `rewind()` and `fseek()` both say everthing worked, `php://input` does not (always) support rewinding the stream.

See http://php.net/manual/en/wrappers.php.php, https://developer.procurios.com/post/2016/07/08/php-input-not-always-what-it-streams and https://stackoverflow.com/questions/3107624/why-can-php-input-be-read-more-than-once-despite-the-documentation-saying-othe for more details on that.

There are two solution:

1. re-open the stream upon `rewind()` or `fseek()`
2. Do not use `php://input` directly, but copy it to another stream inside `ServerRequest::getStreamForBody()`.

Can either of these be implemented? (If needed, I can lend a hand.)

**Comment by pjdietz** [comment]
Thanks for the detailed info in the ticket. I'm going to take a deeper look into this and see if we can find a good solution. In the meantime, you should be able to use the ->detach() method on the body to get the underlying stream handle. This should let you copy it to a temp stream or something else.

**Comment by pjdietz** [comment]
@jorygeerts Version 3.0.6 will let you read the incoming request body stream multiple times. `ServerRequest::getStreamForBody()` copies from `php://input` to a temp stream, so you should be all set. Thanks!

**Comment by jorygeerts** [comment]
Great, thank you very much for the quick response & fix! :)
